<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="UTF-8">
  <meta name="Author" content="">
  <meta name="Keywords" content="">
  <meta name="Description" content="">
  <title> 用户登录 </title>



<script type="text/javascript">
    function MyClick(){
      alert("yse");
    }

</script>

 </head>
    <body>
      <div >sdfsd</div>
      <div >sdfsd2</div>
      <button onclick="MyClick()"> click me </button>
	 </body>
</html>
